### ISSUE TITLE
Add rfdc to benchmark

### ISSUE THREAD

**Issue by sanjuroo** [planttheidea/fast-copy#39]
Currently i am using rfdc library for deep clone, would be interesting to see how it compares using your benchmarks, if i shoul switch. Thanks.

**Comment by planttheidea** [comment]
Feel free to open a PR! I may not get to this right away, cuz life is busy right now.

I have a suspicion, though, it will be faster at the expense of being less correct. I glanced at the source code and it looks to only support arrays, objects, and valid dates. Not a bad thing, just something to consider for your use cases.

**Comment by planttheidea** [comment]
I am going to close this because after some research I've determined the comparison between the libraries is not apples-to-apples. `rfdc` focuses only on the most common use-cases (arrays, objects, valid dates) and ignores several non-JSON use-cases (custom objects / classes, maps, sets, etc). It also does not support circular objects without custom configuration, and in their own documentation they call out the overhead cost of doing so. Due to this, I can basically guarantee it would be faster (likely significantly) for those specific use-cases. For example, testing simple object cloning locally (which is the most apples-to-apples comparison between these libraries), `rfdc` is 3x faster. This is quite impressive considering `fast-copy` is already significantly faster than other common cloning libraries, but it comes with a cost.

Like all other dependency choices, one should weigh the benefits against the costs. If you're usage is exclusive to simple, stringifiable objects, then basically any other cloning library (or even just `JSON.parse(JSON.stringify(object))`) will work for you, and if performance is paramount (like in game development), then `rfdc` is likely your best choice. If you need to support alternative data types, or if you have custom objects via `Object.create`, or if you want to retain the same property descriptors, etc., then `fast-copy` may be for you. Benchmarks are a good data point, but when determining if you should switch (as you put it) a more holistic analysis should be done to see if the support cost is worth the raw speed. `fast-copy` tries to strike a balance between simple support of as many clonable use-cases as possible while also being as fast as possible given that support.

If it helps you, when testing locally `rfdc` significantly outperformed all other libraries by a significant margin, and `fast-copy` specifically by nearly 3x. Only the "simple objects" clone yielded an identical data structure, as more complex data structures (`Map`, `Error`, `RegExp`, custom objects) were ignored or copied incorrectly.
