### ISSUE TITLE
Question: Is this lib faster than the spread operator?

### ISSUE THREAD

**Issue by TK95** [planttheidea/fast-copy#40]
Is there any benchmark or something where this lib is compared to the spread operator?

**Comment by planttheidea** [comment]
No, because that would not be an apples-to-apples comparison. Spread / `Object.assign()` is a shallow copy only, whereas this library performs a deep copy:

```js
const deepObject = { foo: { bar: 'baz' } };
const shallowClone = { ...deepObject };
const deepClone = fastCopy(deepObject);

console.log(shallowClone.foo === deepObject.foo); // true
console.log(deepClone.foo === deepObject.foo); // false
```

If you were to replicate its functionality, it would be something like:

```js
const deepClone = { ...deepObject, foo: { ...deepObject.foo } };
```

But even this is not apples-to-apples, as certain aspects would be lost. An example is an object with a custom prototype; this library would retain that prototype, whereas it would be converted into a standard POJO in a spread scenario.

**Comment by TK95** [comment]
Gotcha. Thanks @planttheidea
