### ISSUE TITLE
Unable to npm i

### ISSUE THREAD

**Issue by benjamin-andersen** [planttheidea/fast-copy#54]
I cloned the project and ran `npm i`. I am on Ubuntu-20.04 with most up-to-date `npm`

![image](https://user-images.githubusercontent.com/70706530/152449488-db366b40-377e-4b77-8d8d-28eeec024234.png)

**Comment by planttheidea** [comment]
I know you closed this, but just following up since I had a sec to give it a try.

I pulled down the latest (fresh `git clone`) and ran `npm i` and didn't have any issues on npm@6, but did get issues on npm@8. I had no issues on yarn, so hopefully that unblocks you.

I believe the issue is the use of `tslint`, which should be updated to ESLint + `@typescript-eslint`, since that is the source of the error (and frankly it should be done anyway, since `tslint` is a dead project). I'll create an issue for the migration.
